[hololens]
package = "holo/lens-npm-run/14"

[hololens.npm-run]
env = "development"
command = "build"
output_dir = "dist"

[hololens.input]
root = "vue/advanced-portfolio-manager"
files = "**"

[hololens.output]
root = "webapp-builds/SlatePortfolioManager"
merge = "replace"
