[hololens]
package = "holo/lens-sencha-app"

[hololens.sencha]
app = "SlateTasksTeacher"

[hololens.input]
root = "sencha-workspace"
files = [
    "workspace.json",
    "ext/**",
    "packages/**",
    "SlateTasksTeacher/**",
]

[hololens.output]
root = "webapp-builds/SlateTasksTeacher"
merge = "replace"