[hololens]
package = "holo/lens-sencha-app"

[hololens.sencha]
workspace = "sencha-workspace"
app = "SlateDemonstrationsStudent"

[hololens.input]
files = [
    "sencha-workspace/SlateDemonstrationsStudent/**",
    "sencha-workspace/packages/jarvus-routing/**",
    "sencha-workspace/packages/slate-theme/**",
    "sencha-workspace/packages/slate-cbl/**",
    "sencha-workspace/packages/slate-cbl-colors/**",
    "sencha-workspace/packages/slate-core-data/**",
    "sencha-workspace/packages/slate-ui-classic/**",
    "sencha-workspace/packages/emergence-apikit/**",
    "sencha-workspace/packages/jarvus-apikit/**",
    "sencha-workspace/packages/jarvus-ext-glyphs/**",
    "sencha-workspace/packages/jarvus-ext-actionevents/**",
    "sencha-workspace/packages/jarvus-lazydata/**",
    "sencha-workspace/packages/jarvus-hotfixes/**",
    "sencha-workspace/ext/**",
    "sencha-workspace/workspace.json",
    "site-root/sass/**/_variables.scss",
    "site-root/sass/**/_variables-*.scss",
]

[hololens.output]
root = "webapp-builds/SlateDemonstrationsStudent"
merge = "replace"