[hololens]
package = "holo/lens-sencha-app"

[hololens.sencha]
app = "SlateTasksManager"

[hololens.input]
root = "sencha-workspace"
files = [
    "workspace.json",
    "ext/**",
    "packages/**",
    "SlateTasksManager/**",
]

[hololens.output]
root = "webapp-builds/SlateTasksManager"
merge = "replace"