@baseUrl = http://localhost:2190

###

# @name login
POST {{baseUrl}}/login
Accept: application/json
Content-Type: application/x-www-form-urlencoded

_LOGIN[username]=system
&_LOGIN[password]=system
&_LOGIN[returnMethod]=POST

###

# @name getSession
GET {{baseUrl}}/login
Accept: application/json

###

GET {{baseUrl}}/cbl/content-areas
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/competencies
    ?content_area=SCI
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json


###

GET {{baseUrl}}/cbl/skills
    ?content_area=SCI
    # &competencies[]=SCI.1
    # &competencies[]=SCI.2
    # &competencies[]=1
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/student-competencies
    ?entered_via=enrollment
    # &student=aabernathy-2
    &students=section:ELA-001
    &level=9
    &content_area=SCI
    # &competency=SCI.1
    # &competencies[]=SCI.1
    # &competencies[]=SCI.2
    # &competencies[]=1
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/demonstrations
    ?foo=bar
    &student=aabernathy
    # &students=section:ELA-001
    &content_area=ELA
    # &competency=SCI.1
    # &competencies[]=SCI.1
    # &competencies[]=SCI.2
    # &competencies[]=1
    # &skills[]=SCI.1.HS.1
    # &skills[]=SCI.1.HS.2
    # &skills[]=97
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/demonstration-skills
    ?foo=bar
    # &student=aabernathy
    &students=section:ELA-001
    &content_area=ELA
    # &competency=SCI.1
    # &competencies[]=SCI.1
    # &competencies[]=SCI.2
    # &competencies[]=1
    # &skills[]=SCI.1.HS.1
    # &skills[]=SCI.1.HS.2
    # &skills[]=97
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/todos
    ?foo=bar
    &student=23
    &section=ELA-001
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json

###

GET {{baseUrl}}/cbl/student-tasks
    ?foo=bar
    &student=aabernathy
    &section=ELA-001
Authorization: Token {{login.response.body.$.data.Handle}}
Accept: application/json
