#!/bin/bash



[ -z "$(git status --porcelain)" ] || {
    echo >&2 "Your git working tree contains uncommitted changes, you should review and commit these before continuing.";
    echo >&2
    echo >&2 "We can try to stash your changes temporarily and re-apply them after pulling. This usually works fine, but if it doesn't you might need to use some advanced git commands to get things back in order."
    echo >&2

    read -p "Press enter to attempt to automatically stash and restore changes, or press CTRL+C to abort this script and sort things out yourself first."

    echo >&2
    echo >&2 "--> Stashing all changes..."
    git stash -u || { echo >&2 "Stash failed"; exit 1; }
    _stash_saved=true
}


echo >&2
echo >&2 "--> Fetching all remotes..."
git fetch --all


echo >&2
echo >&2 "--> Pulling current remote..."
git pull --rebase


echo >&2
echo >&2 "--> Updating/initializing submodules..."
git submodule update --init


[ -n "${_stash_saved}" ] && {
    echo >&2
    echo >&2 "--> Restoring stashed changes..."
    git stash pop
}