<template>
  <v-data-table
    v-model:items-per-page="itemsPerPage"
    :headers="headers"
    :items="tasks"
    density="compact"
    item-value="name"
    class="elevation-1"
  >
    <template v-slot:column.ParentTask="{ column }">
        <ParentTaskColumnTemplate :column="column" />
    </template>
    <template v-slot:item.ParentTask="{ item }">
        <ParentTaskItemTemplate :item="item" />
    </template>
    <template v-slot:item.Creator="{ item }">
        <CreatorItemTemplate :item="item" />
    </template>
    <template v-slot:item.Created="{ item }">
        <CreatedItemTemplate :item="item" />
    </template>

  </v-data-table>
</template>

<script>
import ParentTaskColumnTemplate from "@/components/templates/ParentTaskColumnTemplate";
import ParentTaskItemTemplate from "@/components/templates/ParentTaskItemTemplate";
import CreatedItemTemplate from "@/components/templates/CreatedItemTemplate.vue";
import CreatorItemTemplate from "@/components/templates/CreatorItemTemplate.vue";

export default {
  components: {
    ParentTaskColumnTemplate,
    ParentTaskItemTemplate,
    CreatorItemTemplate,
    CreatedItemTemplate
  },
  data() {
    return {
      itemsPerPage: 20,
      headers: [
        { title: "Title", align: "start", key: "Title" },
        { title: "Subtask of", align: "start", key: "ParentTask" },
        { title: "Type of Exp.", align: "center", key: "ExperienceType" },
        { title: "Skills", align: "end", key: "Skills" },
        { title: "Created by", align: "start", key: "Creator" },
        { title: "Created", align: "end", key: "Created" },
      ],
      tasks: [
        {
          ID: 46,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1666973602,
          CreatorID: 3,
          RevisionID: null,
          Modified: 1666973827,
          ModifierID: 3,
          SectionID: 0,
          Title: "A Shared Task",
          Handle: "a_shared_task",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions:
            "A shared task that will be used to test the filtering of shared and unshared tasks",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 3,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 3,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 61,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017554,
              ModifierID: null,
              CompetencyID: 15,
              Code: "MATH.1.1",
              Descriptor: "Gather and organize information",
              Statement:
                "How well can I gather and organize information when solving a problem?",
              DemonstrationsRequired: {
                9: 4,
                10: 4,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 62,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017554,
              ModifierID: null,
              CompetencyID: 15,
              Code: "MATH.1.2",
              Descriptor: "Model the problem",
              Statement: "How well can I model the problem?",
              DemonstrationsRequired: {
                9: 4,
                10: 4,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: null,
          Attachments: [],
          ClonedTask: null,
        },
        {
          ID: 45,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297685,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Reflection: Who Gets a Vote",
          Handle: "reflection--who_gets_a_vote",
          ParentTaskID: null,
          ClonedTaskID: 21,
          Status: "shared",
          Instructions: "Complete the reflection google form.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 38,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 8,
              Code: "HOS.1.4",
              Descriptor: "Improve my work",
              Statement: "How well do I revise and improve my work?",
              DemonstrationsRequired: {
                9: 4,
                10: 4,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 39,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 9,
              Code: "HOS.2.1",
              Descriptor: "Monitor and manage my learning",
              Statement:
                "How well do I use my competency dashboard and my PLP to monitor my progress?",
              DemonstrationsRequired: {
                9: 4,
                10: 4,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 119,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017555,
              ModifierID: null,
              CompetencyID: 18,
              Code: "NGE.1.5",
              Descriptor: "Reflect on my work and my impact",
              Statement: "How well do I reflect on my work and on my impact?",
              DemonstrationsRequired: {
                9: 1,
                10: 3,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: null,
          Attachments: [],
          ClonedTask: {
            ID: 21,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622292679,
            CreatorID: 3,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 6,
            Title: "Reflection: The Art of Resistance",
            Handle: "reflection--the_art_of_resistance",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete the reflection google form.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
        },
        {
          ID: 44,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297574,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.6 Step.5: Conclusion",
          Handle: "m.6_step.5--conclusion",
          ParentTaskID: 39,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 14,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.5",
              Descriptor: "Provide a compelling conclusion",
              Statement: "How effectively do I conclude my argument?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 39,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622297108,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.6: How Do We Improve Voter Turnout?",
            Handle: "milestone.6--how_do_we_improve_voter_turnout",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Using all feedback, finalize your paper and submit.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 69,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297574,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 44,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/presentation/d/1xIvp-JuzlC9TGPKQ6jd5mw2SwPXSRcd8T-rxh-CDGys/edit#slide=id.p",
            },
            {
              ID: 70,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297574,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 44,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1Dbulea85pBuiV0KcC1bCQtucT5xm7ZJfVe1BacBj9Fo/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 43,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297480,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.6 Step.4: Formal Style",
          Handle: "m.6_step.4--formal_style",
          ParentTaskID: 39,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 13,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.4",
              Descriptor:
                "Use a formal style, objective tone, and advanced vocabulary",
              Statement:
                "How well do I use vocabulary and maintain a formal style and objective tone?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 39,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622297108,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.6: How Do We Improve Voter Turnout?",
            Handle: "milestone.6--how_do_we_improve_voter_turnout",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Using all feedback, finalize your paper and submit.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 67,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297480,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 43,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1wymR5RBryFHNbfxqaIEYb_rckas5RShsYwCAwRoAP64/edit",
            },
            {
              ID: 68,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297480,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 43,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1vM6ZnBlxEloIGVCAoRH8vKdaqaszw1C1zIttk4bwAsY/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 42,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297396,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.6 Step.3: Transitions",
          Handle: "m.6_step.3--transitions",
          ParentTaskID: 39,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 12,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.3",
              Descriptor: "Use words and transitions to create cohesion",
              Statement: "How well do I use transitions to connect my ideas?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 39,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622297108,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.6: How Do We Improve Voter Turnout?",
            Handle: "milestone.6--how_do_we_improve_voter_turnout",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Using all feedback, finalize your paper and submit.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 65,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297396,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 42,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1cM2rjq5dOoMLJoSO1-IxXHCaUjB50dfhclE166ajeNA/edit",
            },
            {
              ID: 66,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297396,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 42,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1n35rjrdc1OfVzfEcb_3u6ryB86-w13dyPDo4_mOqFLY/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 41,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297306,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.6 Step.2: Claim/Counterclaim",
          Handle: "m.6_step.2--claim-counterclaim",
          ParentTaskID: 39,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 11,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.2",
              Descriptor: "Use evidence to develop claims and counterclaims",
              Statement: "How well do I develop my claim and counterclaims?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 39,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622297108,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.6: How Do We Improve Voter Turnout?",
            Handle: "milestone.6--how_do_we_improve_voter_turnout",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Using all feedback, finalize your paper and submit.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 63,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297306,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 41,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1Ac8d2EKwsC7XCbKs4LE9bv8VnSPgr-YxY2McET2rc_8/edit",
            },
            {
              ID: 64,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297307,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 41,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1r5Ay165uIV2uNFh74AQLm4IC47TUEpw6v0qKEhgCNbg/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 40,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297215,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.6 Step.1: Introduce Claim",
          Handle: "m.6_step.1--introduce_claim",
          ParentTaskID: 39,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 10,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.1",
              Descriptor: "Introduce claims",
              Statement: "How well do I introduce my claim?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 39,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622297108,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.6: How Do We Improve Voter Turnout?",
            Handle: "milestone.6--how_do_we_improve_voter_turnout",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Using all feedback, finalize your paper and submit.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 61,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297215,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 40,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/presentation/d/1JLYqItzLG0uhtXnIGahAeInKHpQGinTnG-GOxQ2_Siw/edit#slide=id.p",
            },
            {
              ID: 62,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297215,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 40,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1jxiJedE3AoBcyyG7vJwr7UCa1_SJ4SHRT-GwtMtFuPk/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 39,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297108,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Milestone.6: How Do We Improve Voter Turnout?",
          Handle: "milestone.6--how_do_we_improve_voter_turnout",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Using all feedback, finalize your paper and submit.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 15,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 3,
              Code: "ELA.3.6",
              Descriptor: "Strengthen writing through revision",
              Statement:
                "How well do I strengthen my writing through a revision process?",
              DemonstrationsRequired: {
                9: 1,
                10: 1,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: null,
          Attachments: [],
          ClonedTask: null,
        },
        {
          ID: 38,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622297011,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Milestone.5: How Do We Improve Voter Turnout?",
          Handle: "milestone.5--how_do_we_improve_voter_turnout",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions:
            "Using the resources from the previous milestones, complete the research graphic organizer.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 31,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 7,
              Code: "ELA.7.1",
              Descriptor: "Construct a research question",
              Statement: "How well do I construct my primary question?",
              DemonstrationsRequired: {
                9: 2,
                10: 2,
                11: 3,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 32,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 7,
              Code: "ELA.7.2",
              Descriptor:
                "Identify and select credible, diverse sources to gather evidence",
              Statement:
                "How well can I identify and select credible, diverse sources?",
              DemonstrationsRequired: {
                9: 2,
                10: 2,
                11: 3,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 33,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 7,
              Code: "ELA.7.3",
              Descriptor: "Use systems to organize information gathered",
              Statement: "How well do I organize information from my sources?",
              DemonstrationsRequired: {
                9: 2,
                10: 2,
                11: 3,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
            {
              ID: 34,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 7,
              Code: "ELA.7.4",
              Descriptor: "Synthesize multiple sources",
              Statement: "How well can I evaluate and synthesize my findings?",
              DemonstrationsRequired: {
                9: 2,
                10: 2,
                11: 3,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: null,
          Attachments: [
            {
              ID: 60,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622297011,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 38,
              Title: "Graphic Organizer",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1ExfUhQ8SXwoLnGv4l-fgGeBGztrB9MRrYkgbjZeWtKk/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 37,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296868,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.4 Step.2: Venn Diagram",
          Handle: "m.4_step.2--venn_diagram",
          ParentTaskID: 35,
          ClonedTaskID: null,
          Status: "shared",
          Instructions:
            "Create a venn diagram using the text set from the previous step.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 159,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 29,
              Code: "SS.1.2",
              Descriptor: "Analyze multiple perspectives",
              Statement:
                "How well can I analyze factors that shaped perspectives of people in the past?",
              DemonstrationsRequired: {
                9: 3,
                10: 2,
                11: 3,
                12: 3,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 35,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622296567,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.4: Should Voting Be Mandatory?",
            Handle: "milestone.4--should_voting_be_mandatory",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete both steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 59,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296868,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 37,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1CzmTgdC-wXarYMrey6tgyB4KwGI4oopdBbOh-5gTLzo/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 36,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296734,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.4 Step.1: Examine Text Set",
          Handle: "m.4_step.1--examine_text_set",
          ParentTaskID: 35,
          ClonedTaskID: 35,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 160,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 29,
              Code: "SS.1.3",
              Descriptor: "Analyze historical sources",
              Statement: "How well can I analyze historical sources?",
              DemonstrationsRequired: {
                9: 3,
                10: 2,
                11: 3,
                12: 3,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 35,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622296567,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.4: Should Voting Be Mandatory?",
            Handle: "milestone.4--should_voting_be_mandatory",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete both steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 55,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296734,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 36,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1TF8N9oLYA_xiJWIzYUxl4Q2EXZoi5zvhbWQEokwr9mA/edit",
            },
            {
              ID: 56,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296734,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 36,
              Title: "Mandatory Voting Would Be a Disaster",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1PxOeGH7U48j1BJE7c2YiiVpWri8tLx_aWf2892XGzZA/edit#heading=h.lprqruw1anza",
            },
            {
              ID: 57,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296734,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 36,
              Title: "Make Voting Mandatory in the U.S.",
              Status: "normal",
              URL: "https://drive.google.com/file/d/1YtCYmyh_zKPF89zVtxOZO_UJIYN6XFd3/view",
            },
            {
              ID: 58,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296734,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 36,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1Lt3S_bTkHL7-8xk5zw4r_tZWpGZbomJvP-7H4g9voiw/edit",
            },
          ],
          ClonedTask: {
            ID: 35,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622296567,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.4: Should Voting Be Mandatory?",
            Handle: "milestone.4--should_voting_be_mandatory",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete both steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
        },
        {
          ID: 35,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296567,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Milestone.4: Should Voting Be Mandatory?",
          Handle: "milestone.4--should_voting_be_mandatory",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete both steps of this milestone.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [],
          ParentTask: null,
          Attachments: [
            {
              ID: 51,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296567,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 35,
              Title: "Instruction",
              Status: "removed",
              URL: "https://docs.google.com/document/d/1TF8N9oLYA_xiJWIzYUxl4Q2EXZoi5zvhbWQEokwr9mA/edit",
            },
            {
              ID: 52,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296567,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 35,
              Title: "Mandatory Voting Would Be a Disaster",
              Status: "removed",
              URL: "https://docs.google.com/document/d/1PxOeGH7U48j1BJE7c2YiiVpWri8tLx_aWf2892XGzZA/edit#heading=h.lprqruw1anza",
            },
            {
              ID: 53,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296567,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 35,
              Title: "Make Voting Mandatory in the U.S.",
              Status: "removed",
              URL: "https://drive.google.com/file/d/1YtCYmyh_zKPF89zVtxOZO_UJIYN6XFd3/view",
            },
            {
              ID: 54,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296567,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 35,
              Title: "Assessment",
              Status: "removed",
              URL: "https://docs.google.com/document/d/1Lt3S_bTkHL7-8xk5zw4r_tZWpGZbomJvP-7H4g9voiw/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 34,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296374,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.3 Step.3: Voter turnout relationships",
          Handle: "m.3_step.3--voter_turnout_relationships",
          ParentTaskID: 31,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 168,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 31,
              Code: "SS.3.2",
              Descriptor: "Apply geographic tools",
              Statement:
                "How well can I analyze maps, satellite images, photographs, and other representations to explain relationships between the locations of places and regions and their political, cultural, and economic dynamics?",
              DemonstrationsRequired: {
                9: 2,
                10: 2,
                11: 2,
                12: 2,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 31,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622295979,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.3: Who votes?",
            Handle: "milestone.3--who_votes",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete all three steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 49,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296374,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 34,
              Title: "PA Voter Turnout Map",
              Status: "normal",
              URL: "https://b21.maps.arcgis.com/apps/MapJournal/index.html?appid=2e03df031b2047f69bf219b1b9e761d4",
            },
            {
              ID: 50,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296374,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 34,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/13AWjBv8Cb2JSGYQDrQ8D44cmS4J10hqGBl2muIoxvVI/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 33,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296214,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.3 Step.2: Patterns and changes in voting behavior",
          Handle: "m.3_step.2--patterns_and_changes_in_voting_behavior",
          ParentTaskID: 31,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 162,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 29,
              Code: "SS.1.5",
              Descriptor: "Analyze causes, effects, and continuity and change",
              Statement:
                "How well can I understand, analyze, and explain the causes and effects of an event that demonstrate continuity and/or change?",
              DemonstrationsRequired: {
                9: 3,
                10: 2,
                11: 3,
                12: 3,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 31,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622295979,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.3: Who votes?",
            Handle: "milestone.3--who_votes",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete all three steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 47,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296214,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 33,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/presentation/d/1O9W24_8tLs50lZXIWrJ8amtqRVEPgpKcfFI9uDER0JA/edit#slide=id.p",
            },
            {
              ID: 48,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296214,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 33,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1bBLUw5REl_f4eTSvqCD6WmyyzWLQ3AVQ3Go85GtQSyY/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 32,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622296086,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.3 Step.1: Voter Influences",
          Handle: "m.3_step.1--why_do-don-t_people_vote",
          ParentTaskID: 31,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete the assessment.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 158,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 29,
              Code: "SS.1.1",
              Descriptor: "Evaluate historical outcomes in context",
              Statement:
                "How well can I evaluate historical outcomes in context?",
              DemonstrationsRequired: {
                9: 3,
                10: 2,
                11: 3,
                12: 3,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 31,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622295979,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.3: Who votes?",
            Handle: "milestone.3--who_votes",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete all three steps of this milestone.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 45,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296086,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 32,
              Title: "Instruction",
              Status: "normal",
              URL: "https://docs.google.com/presentation/d/1eT5XbuYilLoI3Eq_Upsbg-dNAvm8dzbpTvrdS7s3Gfs/edit#slide=id.p",
            },
            {
              ID: 46,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622296086,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 32,
              Title: "Assessment",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1LUzROfOy-yEUNZfNIv4FsBh0-fuUf4rz5CsYeD7svKg/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 31,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622295979,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Milestone.3: Who votes?",
          Handle: "milestone.3--who_votes",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete all three steps of this milestone.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [],
          ParentTask: null,
          Attachments: [],
          ClonedTask: null,
        },
        {
          ID: 30,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622295718,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.2 Step.1: Why do/don't people vote?",
          Handle: "m.2_step.1--why_do-don-t_people_vote",
          ParentTaskID: 29,
          ClonedTaskID: null,
          Status: "shared",
          Instructions:
            "Read the articles and then complete and submit the short answer questions.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [],
          ParentTask: {
            ID: 29,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622295572,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.2: What Stops People from Voting?",
            Handle: "milestone.2--what_stops_people_from_voting",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions: "Complete and submit the short answer questions.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 42,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295718,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 30,
              Title: "4 reasons why many people don’t vote",
              Status: "normal",
              URL: "https://drive.google.com/file/d/1P3jNnpX21q4oWUFoNUyFXU7mzCDa8Xan/view",
            },
            {
              ID: 43,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295718,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 30,
              Title: "Why More Young People Don’t Vote",
              Status: "normal",
              URL: "https://www.nytimes.com/2018/10/04/learning/lesson-plans/wasted-ballots-a-lesson-exploring-why-more-young-people-dont-vote-and-what-students-can-do-about-it.html",
            },
            {
              ID: 44,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295718,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 30,
              Title: "Short Answer Questions",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1UZu2-V7s26XMtRbXrbFgWsQY90IYmkDn-Q8YWAiiZIE/edit",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 29,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622295572,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "Milestone.2: What Stops People from Voting?",
          Handle: "milestone.2--what_stops_people_from_voting",
          ParentTaskID: null,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the short answer questions.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 161,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017556,
              ModifierID: null,
              CompetencyID: 29,
              Code: "SS.1.4",
              Descriptor:
                "Evaluate the importance of people's actions in shaping outcomes",
              Statement:
                "How well can I evaluate the importance of people's actions in shaping historical events?",
              DemonstrationsRequired: {
                9: 3,
                10: 2,
                11: 3,
                12: 3,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: null,
          Attachments: [
            {
              ID: 37,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295572,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 29,
              Title: "Short Answer Questions",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1hF2R1kI8YeSfVGoyXBBRKcyEd5_Jad0mXh4ugSaR1z4/edit",
            },
            {
              ID: 38,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295572,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 29,
              Title: "All In: The Fight for American Democracy",
              Status: "normal",
              URL: "https://www.youtube.com/watch?v=avCEHtZlcRs",
            },
            {
              ID: 39,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295572,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 29,
              Title: "Teaching the Truth About Voter Suppression",
              Status: "normal",
              URL: "https://www.learningforjustice.org/magazine/teaching-the-truth-about-voter-suppression",
            },
            {
              ID: 40,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295572,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 29,
              Title:
                "What barriers to voting do Americans face and why does it matter?",
              Status: "normal",
              URL: "https://www.facinghistory.org/educator-resources/current-events/voting-rights-united-states",
            },
            {
              ID: 41,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295572,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 29,
              Title:
                "How Selma's 'Bloody Sunday' Became a Turning Point in the Civil Rights Movement",
              Status: "normal",
              URL: "https://www.history.com/news/selma-bloody-sunday-attack-civil-rights-movement",
            },
          ],
          ClonedTask: null,
        },
        {
          ID: 28,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622295272,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.1 Step.3: Voting Discussion",
          Handle: "m.1_step.3--voting_discussion",
          ParentTaskID: 25,
          ClonedTaskID: null,
          Status: "shared",
          Instructions:
            "You will be scored after being observed in the fishbowl discussion activity.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 29,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 6,
              Code: "ELA.6.2",
              Descriptor: "Pose and respond to questions",
              Statement: "How well do I pose and respond to questions?",
              DemonstrationsRequired: {
                9: 2,
                10: 3,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 25,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622294729,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.1: Who Should Be Able to Vote",
            Handle: "milestone.1--who_should_be_able_to_vote",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions:
              "After the discussion, complete and submit the reflection.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [],
          ClonedTask: null,
        },
        {
          ID: 27,
          Class: "Slate\\CBL\\Tasks\\ExperienceTask",
          Created: 1622295171,
          CreatorID: 5,
          RevisionID: null,
          Modified: null,
          ModifierID: null,
          SectionID: 7,
          Title: "M.1 Step.2: Argument Planner",
          Handle: "m.1_step.2--argument_planner",
          ParentTaskID: 25,
          ClonedTaskID: null,
          Status: "shared",
          Instructions: "Complete and submit the argument planner.",
          DueDate: null,
          ExpirationDate: null,
          ExperienceType: "Studio",
          Creator: {
            ID: 5,
            Class: "Emergence\\People\\User",
            Created: 1546398245,
            CreatorID: null,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            FirstName: "Teacher2",
            LastName: "Slate",
            MiddleName: null,
            PreferredName: null,
            NameSuffix: null,
            Gender: null,
            BirthDate: null,
            Location: null,
            About: null,
            PrimaryPhotoID: null,
            PrimaryEmailID: 5,
            PrimaryPhoneID: null,
            PrimaryPostalID: null,
            Username: "teacher2",
            AccountLevel: "Staff",
            TemporaryPassword: null,
          },
          Skills: [
            {
              ID: 28,
              Class: "Slate\\CBL\\Skill",
              Created: 1546398245,
              CreatorID: 1,
              RevisionID: null,
              Modified: 1676017553,
              ModifierID: null,
              CompetencyID: 6,
              Code: "ELA.6.1",
              Descriptor: "Demonstrate preparedness and responsibility",
              Statement: "How well do I participate in the discussion?",
              DemonstrationsRequired: {
                9: 2,
                10: 3,
                11: 4,
                12: 4,
                default: 1,
              },
              Status: "active",
            },
          ],
          ParentTask: {
            ID: 25,
            Class: "Slate\\CBL\\Tasks\\ExperienceTask",
            Created: 1622294729,
            CreatorID: 5,
            RevisionID: null,
            Modified: null,
            ModifierID: null,
            SectionID: 7,
            Title: "Milestone.1: Who Should Be Able to Vote",
            Handle: "milestone.1--who_should_be_able_to_vote",
            ParentTaskID: null,
            ClonedTaskID: null,
            Status: "shared",
            Instructions:
              "After the discussion, complete and submit the reflection.",
            DueDate: null,
            ExpirationDate: null,
            ExperienceType: "Studio",
          },
          Attachments: [
            {
              ID: 33,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295171,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 27,
              Title:
                "Millions of Americans can't vote for president because of where they live",
              Status: "normal",
              URL: "https://www.pri.org/stories/2016-11-01/millions-americans-cant-vote-president-because-where-they-live",
            },
            {
              ID: 34,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295171,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 27,
              Title:
                "Should those who have committed serious crimes be allowed to vote?",
              Status: "normal",
              URL: "https://drive.google.com/file/d/158bYzMJRIiHir_5MzNwv01u6paHWqDnh/view",
            },
            {
              ID: 35,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295171,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 27,
              Title:
                "Support is growing for lowering the voting age from 18 to 16",
              Status: "normal",
              URL: "https://drive.google.com/file/d/1WxOsNLq2FIsxoq6k5C0DWDEtkz8AqK3v/view",
            },
            {
              ID: 36,
              Class: "Slate\\CBL\\Tasks\\Attachments\\Link",
              Created: 1622295171,
              CreatorID: 5,
              ContextClass: "Slate\\CBL\\Tasks\\Task",
              ContextID: 27,
              Title: "Argument Planner",
              Status: "normal",
              URL: "https://docs.google.com/document/d/1KTs50gxlDkA5kMbcmMINq74mbSukTOXnsmNrBpKXv8s/edit",
            },
          ],
          ClonedTask: null,
        },
      ],
    };
  },
};
</script>
