[holomapping]
files = [
    "*/**",

    # exclude CI and developer assets
    "!.github/",
    "!.vscode/",
    "!books/",
    "!cypress/",
    "!docs/",
    "!fixtures/",
    "!habitat/",
    "!helm-chart/",
    "!php-config/Git.config.d/",
    "!script/",

    # exclude submodules that support local Sencha app development
    # -- they would overwrite the trees coming in the right way through projection
    "!sencha-workspace/ext",
    "!sencha-workspace/packages.remote/",
    "!sencha-workspace/.sencha/",
    "!sencha-workspace/workspace.json",
    "!sencha-workspace/plan.abstract.sh"
]
after = "*"
