[holomapping]
files = [
    "*/**",
    "!.github/",
    "!.vscode/",
    "!books/",
    "!php-config/Git.config.d/",
    "!script/",

    # exclude the submodules we're using temporarily to support local dev
    # -- they would overwrite the trees coming in the right way through projection
    "!sencha-workspace/ext",
    "!sencha-workspace/packages.remote/",
    "!sencha-workspace/.sencha/",
    "!sencha-workspace/workspace.json",
    "!sencha-workspace/plan.abstract.sh"
]
after = "*"
