graph TD
    VIEW_MAIN[Dashboard View]

    NAV_USER_HASH --> |Browser-driven navigation| ROUTER
    NAV_ROUTER_HASH --> |App-driven navigation| ROUTER

    CTRL_DASH_ROUTER --> |"setStudent(...)"| VIEW_MAIN
    CTRL_DASH_ROUTER --> |"setSection(...)"| VIEW_MAIN

    VIEW_MAIN -.-> |"control: { studentchange }"| CTRL_DASH_CHANGE
    VIEW_MAIN -.-> |"control: { sectionchange }"| CTRL_DASH_CHANGE
    VIEW_MAIN -.-> |"control: { studentchange }"| CTRL_TASKS
    VIEW_MAIN -.-> |"control: { sectionchange }"| CTRL_TASKS
    VIEW_MAIN -.-> |"control: { studentchange }"| CTRL_TODOS
    VIEW_MAIN -.-> |"control: { sectionchange }"| CTRL_TODOS


    subgraph User navigates via browser
        NAV_USER_HASH>Browser Address Bar]
    end

    subgraph User navigates via UI components
        NAV_STUDENT_IN>Student Selector]
        NAV_SECTION_IN>Section Selector]
        CTRL_MAIN_NAV("
            Dashboard Controller
            <code>
                <li>onStudentSelectorSelect</li>
                <li>onStudentSelectorClear</li>
                <li>onSectionSelectorSelect</li>
                <li>onSectionSelectorClear</li>
            </code>
        ")

        NAV_STUDENT_IN -.-> |select| CTRL_MAIN_NAV
        NAV_STUDENT_IN -.-> |clear| CTRL_MAIN_NAV
        NAV_SECTION_IN -.-> |select| CTRL_MAIN_NAV
        NAV_SECTION_IN -.-> |clear| CTRL_MAIN_NAV

        CTRL_MAIN_NAV --> |"redirectTo(...)"| NAV_ROUTER_HASH
    end

    subgraph Route parameters applied to top-level view state
        NAV_ROUTER_HASH>Browser Address Bar]
        ROUTER(Ext.app.route.Router)
        CTRL_DASH_ROUTER("
            Dashboard Controller
            <code>
                <li>showDashboard(studentUsername, sectionCode)</li>
            </code>
        ")

        ROUTER --> |"routes: { ':studentUsername/:sectionCode' }"| CTRL_DASH_ROUTER
    end

    subgraph New state propagates throughout application
        CTRL_TASKS("
            Tasks Controller
            <code>
                <li>onStudentChange</li>
                <li>onSectionChange</li>
            </code>
        ")
        CTRL_TODOS("
            Todos Controller
            <code>
                <li>onStudentChange</li>
                <li>onSectionChange</li>
            </code>
        ")
        STORE_TASKS((Tasks Store))
        STORE_TODOS((Todos Store))
        VIEW_TASKS[Tasks View]
        VIEW_TODOS[Todos View]

        CTRL_TASKS --> |"setReadOnly(...)"| VIEW_TASKS
        CTRL_TASKS --> |"setStudent(...)"| STORE_TASKS
        CTRL_TASKS --> |"setSection(...)"| STORE_TASKS

        CTRL_TODOS --> |"setReadOnly(...)"| VIEW_TODOS
        CTRL_TODOS --> |"setStudent(...)"| STORE_TODOS
        CTRL_TODOS --> |"setSection(...)"| STORE_TODOS

        STORE_TASKS -.-> |data events| VIEW_TASKS
        STORE_TODOS -.-> |data events| VIEW_TODOS

        VIEW_TASKS -.-> |User Intents| CTRL_TASKS
        VIEW_TODOS -.-> |User Intents| CTRL_TODOS
    end

    subgraph New state reflected back to all navigation UI
        CTRL_DASH_CHANGE("
            Dashboard Controller
            <code>
                <li>onStudentChange</li>
                <li>onSectionChange</li>
            </code>
        ")
        NAV_STUDENT_OUT>Student Selector]
        NAV_SECTION_OUT>Section Selector]

        CTRL_DASH_CHANGE --> |"setValue(...)"| NAV_STUDENT_OUT
        CTRL_DASH_CHANGE --> |"setValue(...)"| NAV_SECTION_OUT
    end
