graph TD
    NAV_HASH_IN>Browser URL]
    NAV_SELECTORS_IN>Selection Menus]
    NAV_HASH_OUT>Browser URL]
    NAV_SELECTORS_OUT>Selection Menus]

    CONTROLLER_MAIN_IN(Dashboard Controller)
    CONTROLLER_MAIN_OUT(Dashboard Controller)
    CONTROLLER_TASKS(Tasks Controller)
    CONTROLLER_TODOS(Todos Controller)

    STORE_TASKS((Tasks Store))
    STORE_TODOS((Todos Store))

    VIEW_MAIN[Dashboard View]
    VIEW_TASKS[Tasks View]
    VIEW_TODOS[Todos View]

    subgraph User navigates via browser or in-app menus
        NAV_HASH_IN -.-> |Browser Navigation| CONTROLLER_MAIN_IN
        NAV_SELECTORS_IN -.-> |User Intents| CONTROLLER_MAIN_IN
    end

    subgraph New values detected and applied to state
        CONTROLLER_MAIN_IN --> |"setStudent()"| VIEW_MAIN
        CONTROLLER_MAIN_IN --> |"setSection()"| VIEW_MAIN
    end

    subgraph New state propagated throughout application
        VIEW_MAIN -.-> |studentchange| CONTROLLER_TASKS
        VIEW_MAIN -.-> |sectionchange| CONTROLLER_TASKS
        VIEW_MAIN -.-> |sectionchange| CONTROLLER_TODOS
        VIEW_MAIN -.-> |sectionchange| CONTROLLER_TODOS

        CONTROLLER_TASKS --> |"setReadOnly(...)"| VIEW_TASKS
        CONTROLLER_TASKS --> |"setStudent(...)"| STORE_TASKS
        CONTROLLER_TASKS --> |"setSection(...)"| STORE_TASKS

        CONTROLLER_TODOS --> |"setReadOnly(...)"| VIEW_TODOS
        CONTROLLER_TODOS --> |"setStudent(...)"| STORE_TODOS
        CONTROLLER_TODOS --> |"setSection(...)"| STORE_TODOS

        STORE_TASKS -.-> |data events| VIEW_TASKS
        STORE_TODOS -.-> |data events| VIEW_TODOS

        VIEW_TASKS -.-> |User Intents| CONTROLLER_TASKS
        VIEW_TODOS -.-> |User Intents| CONTROLLER_TODOS
    end

    subgraph Navigation reflects new state
        VIEW_MAIN -.-> |studentchange| CONTROLLER_MAIN_OUT
        VIEW_MAIN -.-> |sectionchange| CONTROLLER_MAIN_OUT
        CONTROLLER_MAIN_OUT --> |"redirectTo(...)"| NAV_HASH_OUT
        CONTROLLER_MAIN_OUT --> |"setValue(...)"| NAV_SELECTORS_OUT
    end